[package]
name = "solder"
version = "0.1.0"
authors = ["Kinrezc <matt.czernik@gmail.com>"]
edition = "2018"

[lib]
name = "solder"
path = "src/solder/lib.rs"

[[bin]]
name = "solder"
test = false
doc = false

[dependencies]
serde_json = "1.0.44"
structopt = "0.2.10"
regex = "1"
